
services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app-new
    ports:
      - "8000:8000"
    command: "uvicorn application.api.main:create_app --factory --reload --host 0.0.0.0 --port 8000"



    # env_file:
    #   - .env
    # volumes:
    #   - ./app:/app